// <auto-generated />
using System;
using ChargeNet.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChargeNet.Services.Migrations
{
    [DbContext(typeof(ChargeNetDbContext))]
    [Migration("20260516134402_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChargeNet.Services.Database.ChargingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EnergyConsumedKWh")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TariffId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("TariffId");

                    b.HasIndex("UserId");

                    b.ToTable("ChargingSessions");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.ChargingStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Has24hAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCCS")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCHAdeMO")
                        .HasColumnType("bit");

                    b.Property<bool>("HasIndoor")
                        .HasColumnType("bit");

                    b.Property<bool>("HasType2")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsFastCharger")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("MaxPowerKW")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(2,1)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("StatusId");

                    b.ToTable("ChargingStations");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(3804),
                            Name = "Sarajevo",
                            PostalCode = "71000"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(4234),
                            Name = "Banja Luka",
                            PostalCode = "78000"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(4236),
                            Name = "Tuzla",
                            PostalCode = "75000"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(4237),
                            Name = "Mostar",
                            PostalCode = "88000"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(4238),
                            Name = "Zenica",
                            PostalCode = "72000"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(4239),
                            Name = "Zagreb",
                            PostalCode = "10000"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 2,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(4240),
                            Name = "Split",
                            PostalCode = "21000"
                        });
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargingStationId")
                        .HasColumnType("int");

                    b.Property<int>("ConnectorTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PowerKW")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorTypeId");

                    b.HasIndex("ChargingStationId", "ConnectorTypeId", "Label")
                        .IsUnique()
                        .HasFilter("[Label] IS NOT NULL");

                    b.ToTable("Connectors");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.ConnectorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PowerRating")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ConnectorTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 272, DateTimeKind.Utc).AddTicks(9534),
                            Description = "IEC 62196-2 Type 2 (Mennekes)",
                            Name = "Type 2",
                            PowerRating = 43.0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(316),
                            Description = "Combined Charging System (Combo 2)",
                            Name = "CCS",
                            PowerRating = 350.0m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(319),
                            Description = "CHAdeMO DC fast charging",
                            Name = "CHAdeMO",
                            PowerRating = 62.5m
                        });
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BIH",
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(2665),
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HRV",
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(3043),
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SRB",
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(3045),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SVN",
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(3046),
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 5,
                            Code = "MNE",
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(3047),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 6,
                            Code = "DEU",
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(3048),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AUT",
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(3049),
                            Name = "Austria"
                        });
                });

            modelBuilder.Entity("ChargeNet.Services.Database.FaultReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargingStationId")
                        .HasColumnType("int");

                    b.Property<int?>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("UserId");

                    b.ToTable("FaultReports");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.LoyaltyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Tier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalChargedKWh")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoyaltyPrograms");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargingStationId")
                        .HasColumnType("int");

                    b.Property<int?>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReservationEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId", "StatusId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.ReservationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReservationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(1171),
                            Description = "Awaiting confirmation",
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(1543),
                            Description = "Reservation confirmed",
                            Name = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(1546),
                            Description = "Reservation rejected",
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(1547),
                            Description = "Cancelled by user",
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(1549),
                            Description = "Successfully used",
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(1550),
                            Description = "Reservation expired",
                            Name = "Expired"
                        });
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 272, DateTimeKind.Utc).AddTicks(2323),
                            Description = "Full system access",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 272, DateTimeKind.Utc).AddTicks(2821),
                            Description = "Station technician",
                            Name = "Technician"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 272, DateTimeKind.Utc).AddTicks(2823),
                            Description = "Mobile application user and EV driver",
                            Name = "Driver"
                        });
                });

            modelBuilder.Entity("ChargeNet.Services.Database.ServiceOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ChargingStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FaultReportId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId");

                    b.HasIndex("FaultReportId");

                    b.ToTable("ServiceOrders");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.StationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 272, DateTimeKind.Utc).AddTicks(8042),
                            Description = "Operational",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 272, DateTimeKind.Utc).AddTicks(8412),
                            Description = "Temporarily unavailable",
                            Name = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 272, DateTimeKind.Utc).AddTicks(8414),
                            Description = "Under maintenance",
                            Name = "Maintenance"
                        });
                });

            modelBuilder.Entity("ChargeNet.Services.Database.StationVector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargingStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Has24hAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCCS")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCHAdeMO")
                        .HasColumnType("bit");

                    b.Property<bool>("HasIndoor")
                        .HasColumnType("bit");

                    b.Property<bool>("HasType2")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFastCharger")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastComputedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MaxPowerKW")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(2,1)");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId")
                        .IsUnique();

                    b.ToTable("StationVectors");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<TimeSpan?>("EndHour")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerKWh")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("PricePerMinute")
                        .HasColumnType("decimal(10,4)");

                    b.Property<TimeSpan?>("StartHour")
                        .HasColumnType("time");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(7965),
                            Currency = "EUR",
                            IsActive = true,
                            Name = "Standard Day",
                            PricePerKWh = 0.25m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(8576),
                            Currency = "EUR",
                            EndHour = new TimeSpan(0, 6, 0, 0, 0),
                            IsActive = true,
                            Name = "Night Saver",
                            PricePerKWh = 0.15m,
                            StartHour = new TimeSpan(0, 22, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(8914),
                            Currency = "EUR",
                            IsActive = true,
                            Name = "Fast Charge Premium",
                            PricePerKWh = 0.45m,
                            PricePerMinute = 0.05m
                        });
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ChargingSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChargingSessionId");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasFilter("[StripePaymentIntentId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(6345),
                            Email = "admin@chargenet.com",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "ChargeNET",
                            PasswordHash = "$2a$11$PLACEHOLDER_HASH_ADMIN_PASSWORD",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            CreatedAt = new DateTime(2026, 5, 16, 13, 44, 1, 273, DateTimeKind.Utc).AddTicks(7353),
                            Email = "demo@chargenet.com",
                            FirstName = "Demo",
                            IsDeleted = false,
                            LastName = "Driver",
                            PasswordHash = "$2a$11$PLACEHOLDER_HASH_DEMO_PASSWORD",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("ChargeNet.Services.Database.UserStationProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargingStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastVisitedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LikeStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalRating")
                        .HasColumnType("decimal(2,1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VisitedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId");

                    b.HasIndex("UserId", "ChargingStationId")
                        .IsUnique();

                    b.ToTable("UserStationProfiles");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.UserWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasFilter("[StripeCustomerId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserWallets");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BatteryCapacity")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ConnectorTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorTypeId");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasFilter("[LicensePlate] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.ChargingSession", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.Connector", "Connector")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargeNet.Services.Database.Reservation", "Reservation")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChargeNet.Services.Database.Tariff", "Tariff")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargeNet.Services.Database.User", "User")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Connector");

                    b.Navigation("Reservation");

                    b.Navigation("Tariff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.ChargingStation", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.City", "City")
                        .WithMany("ChargingStations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargeNet.Services.Database.StationStatus", "Status")
                        .WithMany("ChargingStations")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.City", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Connector", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.ChargingStation", "ChargingStation")
                        .WithMany("Connectors")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChargeNet.Services.Database.ConnectorType", "ConnectorType")
                        .WithMany("Connectors")
                        .HasForeignKey("ConnectorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChargingStation");

                    b.Navigation("ConnectorType");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.FaultReport", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.ChargingStation", "ChargingStation")
                        .WithMany("FaultReports")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargeNet.Services.Database.Connector", "Connector")
                        .WithMany("FaultReports")
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChargeNet.Services.Database.User", "User")
                        .WithMany("FaultReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChargingStation");

                    b.Navigation("Connector");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Invoice", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.Transaction", "Transaction")
                        .WithOne("Invoice")
                        .HasForeignKey("ChargeNet.Services.Database.Invoice", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChargeNet.Services.Database.User", "User")
                        .WithMany("Invoices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.LoyaltyProgram", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.User", "User")
                        .WithOne("LoyaltyProgram")
                        .HasForeignKey("ChargeNet.Services.Database.LoyaltyProgram", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Notification", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Reservation", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.ChargingStation", "ChargingStation")
                        .WithMany("Reservations")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargeNet.Services.Database.Connector", "Connector")
                        .WithMany("Reservations")
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChargeNet.Services.Database.ReservationStatus", "Status")
                        .WithMany("Reservations")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargeNet.Services.Database.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChargingStation");

                    b.Navigation("Connector");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.ServiceOrder", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.ChargingStation", "ChargingStation")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargeNet.Services.Database.FaultReport", "FaultReport")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChargingStation");

                    b.Navigation("FaultReport");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.StationVector", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.ChargingStation", "ChargingStation")
                        .WithOne("StationVector")
                        .HasForeignKey("ChargeNet.Services.Database.StationVector", "ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Transaction", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.ChargingSession", "ChargingSession")
                        .WithMany("Transactions")
                        .HasForeignKey("ChargingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChargeNet.Services.Database.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChargingSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.User", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChargeNet.Services.Database.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.UserStationProfile", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.ChargingStation", "ChargingStation")
                        .WithMany("UserStationProfiles")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChargeNet.Services.Database.User", "User")
                        .WithMany("UserStationProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.UserWallet", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("ChargeNet.Services.Database.UserWallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Vehicle", b =>
                {
                    b.HasOne("ChargeNet.Services.Database.ConnectorType", "ConnectorType")
                        .WithMany("Vehicles")
                        .HasForeignKey("ConnectorTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChargeNet.Services.Database.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectorType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.ChargingSession", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.ChargingStation", b =>
                {
                    b.Navigation("Connectors");

                    b.Navigation("FaultReports");

                    b.Navigation("Reservations");

                    b.Navigation("ServiceOrders");

                    b.Navigation("StationVector");

                    b.Navigation("UserStationProfiles");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.City", b =>
                {
                    b.Navigation("ChargingStations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Connector", b =>
                {
                    b.Navigation("ChargingSessions");

                    b.Navigation("FaultReports");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.ConnectorType", b =>
                {
                    b.Navigation("Connectors");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.FaultReport", b =>
                {
                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Reservation", b =>
                {
                    b.Navigation("ChargingSessions");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.ReservationStatus", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.StationStatus", b =>
                {
                    b.Navigation("ChargingStations");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Tariff", b =>
                {
                    b.Navigation("ChargingSessions");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.Transaction", b =>
                {
                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ChargeNet.Services.Database.User", b =>
                {
                    b.Navigation("ChargingSessions");

                    b.Navigation("FaultReports");

                    b.Navigation("Invoices");

                    b.Navigation("LoyaltyProgram");

                    b.Navigation("Notifications");

                    b.Navigation("Reservations");

                    b.Navigation("Transactions");

                    b.Navigation("UserStationProfiles");

                    b.Navigation("Vehicles");

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
